# Pandas

## Task 1

You should import the necessary libraries. You will use `numpy` and `pandas` libraries.


> Don't forget to import `numpy`, and `pandas` in short form.

In [6]:
import numpy as np
import pandas as pd

## Task 2

Create a `DataFrame` from the given dictionary `data`.

In [72]:
data = pd.DataFrame({
    "Name": ["John", "Emily", "Ryan"],
    "Age": [16, 28, 22],
    "City": ["New York", "Los Angeles", "Chicago"],
})

# write your code here

## Task 3

In this task you should complete the following steps:

### Task 3.1
Display all data for `Age` column for the DataFrame you created in the previous task.

In [116]:
data["Age"]

0   NaN
1   NaN
2   NaN
Name: Age, dtype: float64

### Task 3.2

Add `Salary` column to the `DataFrame` with the values `[50000, 60000, 45000]`.

In [195]:
salary = pd.Series([50000, 50000, 45000], name="Salary")
data["Salary"] = salary

### Task 3.3

Filter the `DataFrame` to show only the rows with the `Age` greater than 18.

In [77]:
data[data["Age"] > 18]

    Name  Age         City  Salary
1  Emily   28  Los Angeles   50000
2   Ryan   22      Chicago   45000

## Task 4

In this task you should complete the following steps:

### Task 4.1

Add new calculated field `Birth year`;

In [78]:
data["Birth year"] = 2025 - data["Age"]

    Name  Age         City  Salary  Birth year
0   John   16     New York   50000        2009
1  Emily   28  Los Angeles   50000        1997
2   Ryan   22      Chicago   45000        2003

### Task 4.2

Add new calculated field `Average age`.

In [79]:
data["Average age"] = data["Age"].mean()

    Name  Age         City  Salary  Birth year  Average age
0   John   16     New York   50000        2009         22.0
1  Emily   28  Los Angeles   50000        1997         22.0
2   Ryan   22      Chicago   45000        2003         22.0

### Task 4.3

Calculate absolute difference between `Age` and `Average age`.

In [80]:
data["Absolute"] = np.abs(data["Age"] - data["Average age"])

    Name  Age         City  Salary  Birth year  Average age  Absolute
0   John   16     New York   50000        2009         22.0       6.0
1  Emily   28  Los Angeles   50000        1997         22.0       6.0
2   Ryan   22      Chicago   45000        2003         22.0       0.0

## Task 5

Complete the following tasks described below.

In [135]:
# Data
data1 = {'Name': ['John', 'Emily', 'Ryan'],
         'Age': [25, 28, 22]}
data2 = {'Name': ['Emily', 'Ryan', 'Mike'],
         'City': ['Los Angeles', 'Chicago', 'Houston']}

data11 = pd.DataFrame({'Name': ['John', 'Emily', 'Ryan'],
         'Age': [25, 28, 22]})
data22 = pd.DataFrame({'Name': ['Emily', 'Ryan', 'Mike'],
         'City': ['Los Angeles', 'Chicago', 'Houston']})

In [136]:
data = pd.merge(data11, data22)

    Name  Age         City
0  Emily   28  Los Angeles
1   Ryan   22      Chicago

In [138]:
data = pd.concat([data11, data22])

    Name   Age         City
0   John  25.0          NaN
1  Emily  28.0          NaN
2   Ryan  22.0          NaN
0  Emily   NaN  Los Angeles
1   Ryan   NaN      Chicago
2   Mike   NaN      Houston

### Task 5.2

You have two `Series` objects `s1` and `s2`. Make default mathematical operations on these two `Series` objects. Such as `+`, `-`, `*`, `/`, `**`, `//`, `%`. Also, filter `s1` and print only even numbers, and `s2` only with odd numbers.

In [15]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])

In [140]:
s = s1 + s2

0     7
1     9
2    11
3    13
4    15
dtype: int64

In [141]:
s = s1 - s2

0   -5
1   -5
2   -5
3   -5
4   -5
dtype: int64

In [142]:
s = s1 * s2

0     6
1    14
2    24
3    36
4    50
dtype: int64

In [143]:
s = s1 / s2

0    0.166667
1    0.285714
2    0.375000
3    0.444444
4    0.500000
dtype: float64

In [144]:
s = s1 ** s2

0          1
1        128
2       6561
3     262144
4    9765625
dtype: int64

In [146]:
s = s2 // s1
s

0    6
1    3
2    2
3    2
4    2
dtype: int64

In [149]:
s = s1 % s2
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [198]:
s = s1[(s1 % 2 == 0) & (s1 != 0)]
s

1    2
3    4
dtype: int64

In [16]:
s = s2[(s2 % 2 != 0) & (s2 != 0)]

1    7
3    9
dtype: int64

### Task 5.3

You have a `Serias` object `s`. Make the following operations on this `Series` object:

* make all words in uppercase without loops;
* get length of each word without loops.

In [17]:
s = pd.Series(["numpy", "pandas", "matplotlib"])

In [20]:
s.str.upper()

0         NUMPY
1        PANDAS
2    MATPLOTLIB
dtype: object

In [22]:
s.str.len()

0     5
1     6
2    10
dtype: int64

## Task 6 Optional

You have a large dataset consisting of a series of numbers. Your task is to calculate the moving average of the series using a window of `5` elements. The moving average is the average of a set of consecutive values in the series, where the window `slides` through the series to compute the average at each position. The goal is to calculate the moving average efficiently and accurately. Also, compare time performance of Python and Pandas solutions.

> Please, note: If you get `nan` while calculating the moving average, you should remove it from the result. Pandas solution should take 1-2 lines of code.

### Python Solution

In the Python solution, a large dataset is generated using random numbers. The moving average is computed by iterating over the dataset using a loop. At each position, a window of 5 elements is created, and the average is calculated by summing the values in the window and dividing by 5.

In [26]:
import random

def unknown_signature():
    # Generate a large dataset
    data = [random.randint(1, 100) for _ in range(10000000)]

    # Calculate the moving average with a window of 5
    moving_averages = []
    for i in range(4, len(data)):
        window = data[i - 4 : i + 1]
        average = sum(window) / 5
        moving_averages.append(average)
    return moving_averages[:10]

%time unknown_signature()

CPU times: user 7.77 s, sys: 250 ms, total: 8.02 s
Wall time: 8.09 s

[53.6, 48.4, 39.0, 48.4, 31.2, 28.6, 46.8, 51.2, 42.8, 49.8]

### Solution using Pandas and Numpy

In [29]:
import time
start = time.time()
data = pd.Series([random.randint(1, 100) for _ in range(10000000)])
moving_avg = data.rolling(5).mean().dropna()
end = time.time()
print(moving_avg)
print("Pandas time:", end - start)

4          56.8
5          50.0
6          49.8
7          51.2
8          55.6
           ...
9999995    50.8
9999996    47.2
9999997    46.6
9999998    59.6
9999999    58.4
Length: 9999996, dtype: float64
Pandas time: 6.6907079219818115