# Pandas

## Task 1

You should import the necessary libraries. You will use `numpy` and `pandas` libraries.


> Don't forget to import `numpy`, and `pandas` in short form.

In [1]:
from itertools import count

import pandas as pd
import numpy as np

## Task 2

Create a `DataFrame` from the given dictionary `data`.

In [6]:
data = {
    "Name": ["John", "Emily", "Ryan"],
    "Age": [16, 28, 22],
    "City": ["New York", "Los Angeles", "Chicago"],
}

df = pd.DataFrame(data)
print(df)

    Name  Age         City
0   John   16     New York
1  Emily   28  Los Angeles
2   Ryan   22      Chicago

## Task 3

In this task you should complete the following steps:

### Task 3.1
Display all data for `Age` column for the DataFrame you created in the previous task.

In [33]:
df["Age"]

0    16
1    28
2    22
Name: Age, dtype: int64

### Task 3.2

Add `Salary` column to the `DataFrame` with the values `[50000, 60000, 45000]`.

In [16]:
df["Salary"] = [50000, 60000, 45000]
print(df)

    Name  Age         City  Salary
0   John   16     New York   50000
1  Emily   28  Los Angeles   60000
2   Ryan   22      Chicago   45000

### Task 3.3

Filter the `DataFrame` to show only the rows with the `Age` greater than 18.

In [18]:
df[df["Age"] > 18]

    Name  Age         City  Salary
1  Emily   28  Los Angeles   60000
2   Ryan   22      Chicago   45000

## Task 4

In this task you should complete the following steps:

### Task 4.1

Add new calculated field `Birth year`;

In [29]:
df["Birth_year"] = 2026 - df["Age"]
print(df)

    Name  Age         City  Salary  Birth_year  Average_age  Abs_diff_age
0   John   16     New York   50000        2010         22.0           6.0
1  Emily   28  Los Angeles   60000        1998         22.0           6.0
2   Ryan   22      Chicago   45000        2004         22.0           0.0

### Task 4.2

Add new calculated field `Average age`.

In [25]:
df["Average_age"] = df["Age"].mean()
print(df)

    Name  Age         City  Salary  Birth_year  Average_age
0   John   16     New York   50000        2010         22.0
1  Emily   28  Los Angeles   60000        1998         22.0
2   Ryan   22      Chicago   45000        2004         22.0

### Task 4.3

Calculate absolute difference between `Age` and `Average age`.

In [28]:
df["Abs_diff_age"] = abs(df["Age"] - df["Average_age"])
print(df)
variance = df["Age"].var()
print("Variance: ", variance)
age_std = df["Age"].std()
print("Standard deviation:", age_std)
age_median = df["Age"].median()
print("Median:", age_median)

    Name  Age         City  Salary  Birth_year  Average_age  Abs_diff_age
0   John   16     New York   50000        2010         22.0           6.0
1  Emily   28  Los Angeles   60000        1998         22.0           6.0
2   Ryan   22      Chicago   45000        2004         22.0           0.0
Variance:  36.0
Standard deviation: 6.0
Median: 22.0

## Task 5

Complete the following tasks described below.

### Task 5.1

You have two dictionaries `data1` and `data2`. Create two `DataFrame` objects from these dictionaries. Then, `concatenate`, and `merge` these two `DataFrame` objects into one `DataFrame` object, and see the difference.

In [32]:
# Data
data1 = {'Name': ['John', 'Emily', 'Ryan'],
         'Age': [25, 28, 22]}
data2 = {'Name': ['Emily', 'Ryan', 'Mike'],
         'City': ['Los Angeles', 'Chicago', 'Houston']}

# create DataFrame objects
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [52]:
# merge
pd.merge(df1, df2, on="Name")

    Name  Age         City
0  Emily   28  Los Angeles
1   Ryan   22      Chicago

In [55]:
# concatenate
frames = [df1, df2]
con = pd.concat(frames)
print(con)

    Name   Age         City
0   John  25.0          NaN
1  Emily  28.0          NaN
2   Ryan  22.0          NaN
0  Emily   NaN  Los Angeles
1   Ryan   NaN      Chicago
2   Mike   NaN      Houston

### Task 5.2

You have two `Series` objects `s1` and `s2`. Make default mathematical operations on these two `Series` objects. Such as `+`, `-`, `*`, `/`, `**`, `//`, `%`. Also, filter `s1` and print only even numbers, and `s2` only with odd numbers.

In [59]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])

In [60]:
# use + operator here
s1 + s2

0     7
1     9
2    11
3    13
4    15
dtype: int64

In [61]:
# use - operator here
s1 - s2

0   -5
1   -5
2   -5
3   -5
4   -5
dtype: int64

In [62]:
# use * operator here
s1 * s2

0     6
1    14
2    24
3    36
4    50
dtype: int64

In [63]:
# use / operator here
s1 / s2

0    0.166667
1    0.285714
2    0.375000
3    0.444444
4    0.500000
dtype: float64

In [64]:
# use ** operator here
s1 ** s2

0          1
1        128
2       6561
3     262144
4    9765625
dtype: int64

In [65]:
# use // operator here
s1 // s2

0    0
1    0
2    0
3    0
4    0
dtype: int64

In [66]:
# use % operator here
s1 % s2

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [68]:
# filter s1 here
s1[s1 % 2 == 0]

1    2
3    4
dtype: int64

In [69]:
# filter s2 here
s2[s2 % 2 == 1]

1    7
3    9
dtype: int64

### Task 5.3

You have a `Serias` object `s`. Make the following operations on this `Series` object:

* make all words in uppercase without loops;
* get length of each word without loops.

In [71]:
s = pd.Series(["numpy", "pandas", "matplotlib"])

In [72]:
# make all words in uppercase
s.str.upper()

0         NUMPY
1        PANDAS
2    MATPLOTLIB
dtype: str

In [73]:
# get length of each word
s.str.len()

0     5
1     6
2    10
dtype: int64

## Task 6 Optional

You have a large dataset consisting of a series of numbers. Your task is to calculate the moving average of the series using a window of `5` elements. The moving average is the average of a set of consecutive values in the series, where the window `slides` through the series to compute the average at each position. The goal is to calculate the moving average efficiently and accurately. Also, compare time performance of Python and Pandas solutions.

> Please, note: If you get `nan` while calculating the moving average, you should remove it from the result. Pandas solution should take 1-2 lines of code.

### Python Solution

In the Python solution, a large dataset is generated using random numbers. The moving average is computed by iterating over the dataset using a loop. At each position, a window of 5 elements is created, and the average is calculated by summing the values in the window and dividing by 5.

In [74]:
import random

def unknown_signature():
    # Generate a large dataset
    data = [random.randint(1, 100) for _ in range(10000000)]

    # Calculate the moving average with a window of 5
    moving_averages = []
    for i in range(4, len(data)):
        window = data[i - 4 : i + 1]
        average = sum(window) / 5
        moving_averages.append(average)
    return moving_averages[:10]

%time unknown_signature()

CPU times: user 5.2 s, sys: 143 ms, total: 5.34 s
Wall time: 5.34 s

[55.6, 53.8, 54.4, 48.2, 61.6, 68.2, 65.2, 60.6, 57.4, 41.2]

### Solution using Pandas and Numpy

In [76]:
# write your code here
import random

data = [random.randint(1, 100) for _ in range(10_000_000)]

In [80]:
import pandas as pd

moving_avg_pandas = pd.Series(data).rolling(5).mean().dropna()
result = moving_avg_pandas.head(10).tolist()
print(result)

[57.6, 60.4, 50.8, 57.4, 54.4, 49.8, 42.8, 43.2, 36.2, 25.0]

In [82]:
import numpy as np

arr = np.array(data)
moving_avg_numpy = np.convolve(arr, np.ones(5)/5, mode="valid")
result = np.round(moving_avg_numpy[:10], 2).tolist()
print(result)

[57.6, 60.4, 50.8, 57.4, 54.4, 49.8, 42.8, 43.2, 36.2, 25.0]