# Pandas

## Task 1

You should import the necessary libraries. You will use `numpy` and `pandas` libraries.


> Don't forget to import `numpy`, and `pandas` in short form.

In [5]:
import numpy as np
import pandas as pd

## Task 2

Create a `DataFrame` from the given dictionary `data`.

In [2]:
data = {
    "Name": ["John", "Emily", "Ryan"],
    "Age": [16, 28, 22],
    "City": ["New York", "Los Angeles", "Chicago"],
}

df = pd.DataFrame(
    {
        "Name": ["John", "Emily", "Ryan"],
        "Age": [16, 28, 22],
        "City":["New York", "Los Angeles", "Chicago"],
    }
)
df

    Name  Age         City
0   John   16     New York
1  Emily   28  Los Angeles
2   Ryan   22      Chicago

## Task 3

In this task you should complete the following steps:

### Task 3.1
Display all data for `Age` column for the DataFrame you created in the previous task.

In [3]:
df["Age"]

0    16
1    28
2    22
Name: Age, dtype: int64

### Task 3.2

Add `Salary` column to the `DataFrame` with the values `[50000, 60000, 45000]`.

In [5]:
df["Salary"] = [50000, 60000, 45000]
df

    Name  Age         City  Salary
0   John   16     New York   50000
1  Emily   28  Los Angeles   60000
2   Ryan   22      Chicago   45000

### Task 3.3

Filter the `DataFrame` to show only the rows with the `Age` greater than 18.

In [6]:
filtered_df = df[df['Age'] > 18]
display(filtered_df)

    Name  Age         City  Salary
1  Emily   28  Los Angeles   60000
2   Ryan   22      Chicago   45000

## Task 4

In this task you should complete the following steps:

### Task 4.1

Add new calculated field `Birth year`;

In [8]:
df["Birth year"] = 2026 - df["Age"]
df

    Name  Age         City  Salary  Birth year
0   John   16     New York   50000        2010
1  Emily   28  Los Angeles   60000        1998
2   Ryan   22      Chicago   45000        2004

### Task 4.2

Add new calculated field `Average age`.

In [9]:
df["Average age"] = df["Age"].mean()
df

    Name  Age         City  Salary  Birth year  Average age
0   John   16     New York   50000        2010         22.0
1  Emily   28  Los Angeles   60000        1998         22.0
2   Ryan   22      Chicago   45000        2004         22.0

### Task 4.3

Calculate absolute difference between `Age` and `Average age`.

In [10]:
res = (df["Age"] - df["Average age"]).abs()
display(res)

0    6.0
1    6.0
2    0.0
dtype: float64

## Task 5

Complete the following tasks described below.

### Task 5.1

You have two dictionaries `data1` and `data2`. Create two `DataFrame` objects from these dictionaries. Then, `concatenate`, and `merge` these two `DataFrame` objects into one `DataFrame` object, and see the difference.

In [11]:
# Data
data1 = {'Name': ['John', 'Emily', 'Ryan'],
         'Age': [25, 28, 22]}
data2 = {'Name': ['Emily', 'Ryan', 'Mike'],
         'City': ['Los Angeles', 'Chicago', 'Houston']}

df1 = pd.DataFrame(
    {
        "Name":['John', 'Emily', 'Ryan'],
        "Age": [25, 28, 22]
    }
)
df2 = pd.DataFrame(
    {
        'Name': ['Emily', 'Ryan', 'Mike'],
        'City': ['Los Angeles', 'Chicago', 'Houston']
    }
)
display(df1)
display(df2)

    Name  Age
0   John   25
1  Emily   28
2   Ryan   22

    Name         City
0  Emily  Los Angeles
1   Ryan      Chicago
2   Mike      Houston

In [12]:
# merge
res = pd.merge(df1, df2)
display(res)

    Name  Age         City
0  Emily   28  Los Angeles
1   Ryan   22      Chicago

In [13]:
# concatenate
res = pd.concat([df1, df2])
print(res)

    Name   Age         City
0   John  25.0          NaN
1  Emily  28.0          NaN
2   Ryan  22.0          NaN
0  Emily   NaN  Los Angeles
1   Ryan   NaN      Chicago
2   Mike   NaN      Houston

### Task 5.2

You have two `Series` objects `s1` and `s2`. Make default mathematical operations on these two `Series` objects. Such as `+`, `-`, `*`, `/`, `**`, `//`, `%`. Also, filter `s1` and print only even numbers, and `s2` only with odd numbers.

In [20]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])

In [21]:
# use + operator here
s1 = s1 + s2
print(s1)

0     7
1     9
2    11
3    13
4    15
dtype: int64

In [22]:
# use - operator here
s1 = s1 - s2
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# use * operator here
s1 = s1 * s2
print(s1)

In [ ]:
# use / operator here
s1 = s1 / s2
print(s1)

In [ ]:
# use ** operator here
s1 = s1 ** s2
print(s1)

In [ ]:
# use // operator here
s1 = s1 // s2
print(s1)

In [ ]:
# use % operator here
s1 = s1 % s2
print(s1)

In [23]:
# filter s1 here
print(s1[s1 % 2 == 0])

In [ ]:
# filter s2 here
print(s2[s2 % 2 != 0])

### Task 5.3

You have a `Serias` object `s`. Make the following operations on this `Series` object:

* make all words in uppercase without loops;
* get length of each word without loops.

In [6]:
s = pd.Series(["numpy", "pandas", "matplotlib"])

In [26]:
# make all words in uppercase
print(s.str.upper())

0         NUMPY
1        PANDAS
2    MATPLOTLIB
dtype: object

In [7]:
# get length of each word
s.str.len()

0     5
1     6
2    10
dtype: int64

## Task 6 Optional

You have a large dataset consisting of a series of numbers. Your task is to calculate the moving average of the series using a window of `5` elements. The moving average is the average of a set of consecutive values in the series, where the window `slides` through the series to compute the average at each position. The goal is to calculate the moving average efficiently and accurately. Also, compare time performance of Python and Pandas solutions.

> Please, note: If you get `nan` while calculating the moving average, you should remove it from the result. Pandas solution should take 1-2 lines of code.

### Python Solution

In the Python solution, a large dataset is generated using random numbers. The moving average is computed by iterating over the dataset using a loop. At each position, a window of 5 elements is created, and the average is calculated by summing the values in the window and dividing by 5.

In [ ]:
import random

def unknown_signature():
    # Generate a large dataset
    data = [random.randint(1, 100) for _ in range(10000000)]

    # Calculate the moving average with a window of 5
    moving_averages = []
    for i in range(4, len(data)):
        window = data[i - 4 : i + 1]
        average = sum(window) / 5
        moving_averages.append(average)
    return moving_averages[:10]

%time unknown_signature()

### Solution using Pandas and Numpy

In [28]:
# write your code here
data = pd.Series(np.random.randint(1, 100, 10_000_000))

moving_avg = data.rolling(window=5).mean()

moving_avg.dropna().head(10)

4     40.4
5     55.8
6     54.0
7     64.0
8     67.8
9     68.0
10    67.8
11    62.6
12    50.4
13    58.4
dtype: float64