# Pandas

## Task 1

You should import the necessary libraries. You will use `numpy` and `pandas` libraries.


> Don't forget to import `numpy`, and `pandas` in short form.

In [1]:
import numpy as np
import pandas as pd

## Task 2

Create a `DataFrame` from the given dictionary `data`.

In [2]:
data = {
    "Name": ["John", "Emily", "Ryan"],
    "Age": [16, 28, 22],
    "City": ["New York", "Los Angeles", "Chicago"],
}

df = pd.DataFrame(data)
df

    Name  Age         City
0   John   16     New York
1  Emily   28  Los Angeles
2   Ryan   22      Chicago

## Task 3

In this task you should complete the following steps:

### Task 3.1
Display all data for `Age` column for the DataFrame you created in the previous task.

In [3]:
df["Age"]

0    16
1    28
2    22
Name: Age, dtype: int64

### Task 3.2

Add `Salary` column to the `DataFrame` with the values `[50000, 60000, 45000]`.

In [4]:
df["Salary"] = [50000, 60000, 45000]
df

    Name  Age         City  Salary
0   John   16     New York   50000
1  Emily   28  Los Angeles   60000
2   Ryan   22      Chicago   45000

### Task 3.3

Filter the `DataFrame` to show only the rows with the `Age` greater than 18.

In [5]:
filtered_df = df[df["Age"] > 18]
filtered_df

    Name  Age         City  Salary
1  Emily   28  Los Angeles   60000
2   Ryan   22      Chicago   45000

## Task 4

In this task you should complete the following steps:

### Task 4.1

Add new calculated field `Birth year`;

In [6]:
current_year = 2025
df["Year of Birth"] = current_year - df["Age"]
df

    Name  Age         City  Salary  Year of Birth
0   John   16     New York   50000           2009
1  Emily   28  Los Angeles   60000           1997
2   Ryan   22      Chicago   45000           2003

### Task 4.2

Add new calculated field `Average age`.

In [7]:
df["Average age"] = df["Age"].mean()
df

    Name  Age         City  Salary  Year of Birth  Average age
0   John   16     New York   50000           2009         22.0
1  Emily   28  Los Angeles   60000           1997         22.0
2   Ryan   22      Chicago   45000           2003         22.0

### Task 4.3

Calculate absolute difference between `Age` and `Average age`.

In [8]:
average_age = df["Age"].mean()
absolute_difference = abs(df["Age"] - average_age)
absolute_difference

0    6.0
1    6.0
2    0.0
Name: Age, dtype: float64

## Task 5

Complete the following tasks described below.

### Task 5.1

You have two dictionaries `data1` and `data2`. Create two `DataFrame` objects from these dictionaries. Then, `concatenate`, and `merge` these two `DataFrame` objects into one `DataFrame` object, and see the difference.

In [9]:
# Data
data1 = {'Name': ['John', 'Emily', 'Ryan'],
         'Age': [25, 28, 22]}
data2 = {'Name': ['Emily', 'Ryan', 'Mike'],
         'City': ['Los Angeles', 'Chicago', 'Houston']}

pd1 = pd.DataFrame(data1)
pd2 = pd.DataFrame(data2)

In [10]:
data_merge = pd.merge(pd1, pd2, how="outer")
data_merge

    Name   Age         City
0   John  25.0          NaN
1  Emily  28.0  Los Angeles
2   Ryan  22.0      Chicago
3   Mike   NaN      Houston

In [11]:
data_concatenate = pd.concat([pd1, pd2], axis=1)
data_concatenate

    Name  Age   Name         City
0   John   25  Emily  Los Angeles
1  Emily   28   Ryan      Chicago
2   Ryan   22   Mike      Houston

### Task 5.2

You have two `Series` objects `s1` and `s2`. Make default mathematical operations on these two `Series` objects. Such as `+`, `-`, `*`, `/`, `**`, `//`, `%`. Also, filter `s1` and print only even numbers, and `s2` only with odd numbers.

In [12]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])

In [13]:
addition = s1 + s2
addition.name = "Addition"
addition

0     7
1     9
2    11
3    13
4    15
Name: Addition, dtype: int64

In [14]:
subtraction = s2 - s1
subtraction.name = "Subtraction"
subtraction

0    5
1    5
2    5
3    5
4    5
Name: Subtraction, dtype: int64

In [15]:
multiplication = s1 * s2
multiplication.name = "Multiplication"
multiplication

0     6
1    14
2    24
3    36
4    50
Name: Multiplication, dtype: int64

In [16]:
division = s2 / s1
division.name = "Division"
division

0    6.000000
1    3.500000
2    2.666667
3    2.250000
4    2.000000
Name: Division, dtype: float64

In [17]:
exponentiation = s1 ** s2
exponentiation.name = "Exponentiation"
exponentiation

0          1
1        128
2       6561
3     262144
4    9765625
Name: Exponentiation, dtype: int64

In [18]:
addit_division = s2 // s1
addit_division.name = "Add Division"
addit_division

0    6
1    3
2    2
3    2
4    2
Name: Add Division, dtype: int64

In [19]:
percentage = s2 % s1
percentage.name = "Percentage"
percentage

0    0
1    1
2    2
3    1
4    0
Name: Percentage, dtype: int64

In [20]:
filtered_s1 = s1.filter(items=[0, 2])
filtered_s1

0    1
2    3
dtype: int64

In [21]:
filtered_s2 = s2.filter(items=[0, 2])
filtered_s2

0    6
2    8
dtype: int64

### Task 5.3

You have a `Serias` object `s`. Make the following operations on this `Series` object:

* make all words in uppercase without loops;
* get length of each word without loops.

In [22]:
s = pd.Series(["numpy", "pandas", "matplotlib"])

In [23]:
upper_case = s.str.upper()
upper_case

0         NUMPY
1        PANDAS
2    MATPLOTLIB
dtype: object

In [24]:
lengths = s.str.len()
lengths

0     5
1     6
2    10
dtype: int64

## Task 6 Optional

You have a large dataset consisting of a series of numbers. Your task is to calculate the moving average of the series using a window of `5` elements. The moving average is the average of a set of consecutive values in the series, where the window `slides` through the series to compute the average at each position. The goal is to calculate the moving average efficiently and accurately. Also, compare time performance of Python and Pandas solutions.

> Please, note: If you get `nan` while calculating the moving average, you should remove it from the result. Pandas solution should take 1-2 lines of code.

### Python Solution

In the Python solution, a large dataset is generated using random numbers. The moving average is computed by iterating over the dataset using a loop. At each position, a window of 5 elements is created, and the average is calculated by summing the values in the window and dividing by 5.

In [25]:
import random

def unknown_signature():
    # Generate a large dataset
    data = [random.randint(1, 100) for _ in range(10000000)]

    # Calculate the moving average with a window of 5
    moving_averages = []
    for i in range(4, len(data)):
        window = data[i - 4 : i + 1]
        average = sum(window) / 5
        moving_averages.append(average)
    return moving_averages[:10]

%time unknown_signature()

CPU times: total: 7.3 s
Wall time: 7.44 s

[57.8, 58.8, 60.2, 48.2, 65.6, 64.4, 61.8, 60.6, 60.6, 57.6]

### Solution using Pandas and Numpy

In [35]:
def unknown_signature_pd():
    array = np.random.randint(0, 100, 10000000)
    series = pd.Series(array)
    windows_size = 5
    windows_sums = np.convolve(series, np.ones(windows_size, dtype=int), "valid")
    return windows_sums[:10].tolist()
    
%time unknown_signature_pd()

CPU times: total: 141 ms
Wall time: 129 ms

[173, 153, 112, 153, 211, 267, 268, 277, 210, 148]